Memorial page
Fikrat2002/Tribute-page pull request #1
Opened 2024-05-24 09:01 UTC by Fikrat2002

This coding for tribute page include html and css...

2024-05-25 05:38 UTC, ahzamir requested changes
### Hi @Fikrat2002 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Copy your HTML file code and paste it to the freecodecamp website Tribute Page project to see which requirements your project is missing solve those missing requirements and mention me here using @ahzamir to re-review your project.

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
![image](https://github.com/Fikrat2002/Tribute-page/assets/96838030/960acd54-de82-42dd-8eb2-4f6fb9b43c7e)
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
❌ You have followed and completed the Survey Form and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
❌ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-25 05:38 UTC, ahzamir commented on index.html
- Some of your codes are not aligned correctly and are not clean.
- Your codes are not alligned correctly and are not clean try to make their spacing right.
- [**Suggession**] - On your HTML file, at the bottom right side of your vscode click on `Spaces`  then click on `Index using spaces`, and then select `2` from there. Then align your components according to the 2 spaces.
- Example:
```
<div>
  <p>...</p>
  <h1>.... </h1>
  <img ... />
</div>
```

2024-05-25 05:38 UTC, ahzamir commented on index.html
> +       <section id="tribute-info"></section>
- Your section is empty!

2024-05-25 06:43 UTC, Fikrat2002 commented on index.html
@ahzamir Sir the problem is that in Freecodecamp css is named as "styles.css" and Vscode does not accept this naming so in Vscode it is "style.css". Now if you want to check it you need to add a "s" after style. I did double checked and brought a tiny change and to me it is passed. SO if it still shows you error just write "styles.css" in link element and it will show you passed as well.

2024-05-26 12:29 UTC, ahzamir approved these changes
### Hi @Fikrat2002 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/Fikrat2002/Tribute-page/assets/96838030/960acd54-de82-42dd-8eb2-4f6fb9b43c7e)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳
![WowOhMyGodGIF](https://github.com/Fikrat2002/Tribute-page/assets/96838030/c430c9b8-1ff0-4ff9-af1f-b6e6e9d4bca6)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Survey Form project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-29 05:14 UTC, merged